In [246]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.11.0.dev20210928
True


In [247]:
# Matrix should be in same dimension to take it as tensor
t1 = torch.tensor([[[1.,2,2.],[1,2,33.]]])
t1

tensor([[[ 1.,  2.,  2.],
         [ 1.,  2., 33.]]])

In [248]:
print(t1.dim())
t1.shape


3


torch.Size([1, 2, 3])

In [249]:
# ARITHMATIC OPERATIONS ON TENSOR
x=torch.tensor(3.)
w=torch.tensor(4. , requires_grad=True)
b=torch.tensor(5. , requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [250]:
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [251]:
# Compute derivative 
print('dy/dy = ',y.backward())

dy/dy =  None


In [252]:
import numpy as np


In [253]:
z = y.detach().numpy()
z

array(17., dtype=float32)

#  LINEAR REGRESSION PREDICT Apple Yield

In [254]:
# INPUT (temp, raifall, humidity)
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]], dtype='float32')

In [255]:
# Targets (apple, oranges)
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

In [256]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [257]:
# linear regression equation is y = w^T * x + b 
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 1.4217, -0.6249, -1.0052],
        [-1.9838,  0.4469,  0.2054]], requires_grad=True)
tensor([0.1172, 1.3314], requires_grad=True)


In [258]:
def model(x):
    return x @ w.t()+b # @ represent matrix multiplication in Pytorch


In [259]:
# Generate prediction
preds = model(inputs)
print(preds)

tensor([[  18.8016, -104.7179],
        [  10.1576, -126.7299],
        [ -18.2453,  -99.4711],
        [  81.0596, -174.2065],
        [ -32.1497,  -78.2780]], grad_fn=<AddBackward0>)


In [260]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [261]:
# RMSE
def rmse(t1, t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [262]:
from math import sqrt

In [263]:
loss = rmse(preds, targets)
print(sqrt(loss))

163.38572913316204


In [264]:
# Compute Gradient 
loss.backward()

In [265]:
print(w)
print("With GRADE:   ",w.grad)
print(b.grad)

tensor([[ 1.4217, -0.6249, -1.0052],
        [-1.9838,  0.4469,  0.2054]], requires_grad=True)
With GRADE:    tensor([[ -4880.7461,  -7510.4199,  -4273.7891],
        [-17771.6113, -18183.6055, -11439.0010]])
tensor([ -64.2752, -208.6807])


In [266]:
# Adjust the weights and reset gradients 
for i in range(100):
    preds = model(inputs)
    loss = rmse(preds, targets)
    loss.backward()
    print(sqrt(loss))
    with torch.no_grad():    
        w-=w.grad*1e-4
        b-=b.grad*1e-4
        w.grad.zero_()
        b.grad.zero_()

163.38572913316204
405.2975373105541
321.2851148123735
254.91845356652783
202.5180933274852
161.17438876493375
128.58647078425474
102.93457323556308
82.77878441024306
66.97864704632552
54.62919659938036
45.01008187843169
37.54532742337087
31.77193624281006
27.316207110403113
23.876395778898978
21.210402272252672
19.12664508600747
17.47652757595974
16.147409407282836
15.055823654909563
14.141064716056954
13.359641695985607
12.680622510581228
12.082052088367092
11.548253205554916
11.067928727891394
10.632755097199938
10.236474021391594
9.874235872087379
9.542174035677007
9.237105170911315
8.956342987621346
8.69755883004253
8.458709057009397
8.2379580380528
8.033659695951252
7.844316074568539
7.668556754390783
7.5051313012904295
7.3528964609020635
7.21081529639815
7.077918582289537
6.953360358551749
6.836333693875939
6.7261161700427206
6.622067936259897
6.523594508308888
6.430145803551553
6.3412669165694115
6.256499306268317
6.175461588916382
6.097809207422528
6.023215521100258
5.95140166

In [267]:
preds

tensor([[ 57.6589,  70.5696],
        [ 78.4612, 100.1350],
        [126.4186, 133.7610],
        [ 23.4324,  37.1473],
        [ 94.0541, 118.3956]], grad_fn=<AddBackward0>)

In [268]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])